### ISSUE TITLE
[Bug] Single door on double doors are open for some

### ISSUE THREAD

**Issue by Baxxster** [overextended/ox_doorlock#22] opened 2022-05-18 01:57 UTC
I've noticed that one of the two doors on multiple double doors are open for some people, but closed for others.

Which means one door is frozen shut, the other swings openly on some clients.

These doors were created before the recent release, I am not sure if the recent release fixed some bugs related to this, and if I have to remake all the doubledoors?

**Comment by thelindat** [comment] 2022-05-18 08:38
Created or converted?

Note these doors aren’t networked so the only thing synced is the state, so one client might show locked and another unlocked.

Could just be the bad heading though.

**Comment by Baxxster** [comment] 2022-05-18 11:15
They were created.

It seems very random when it happens and who it happens too.
Our server runs onesync and as its not networked, can I assume that the clients getting the update doesn't match the entity data when they arrive, or am I thinking wrong here?

**Comment by thelindat** [comment] 2022-05-19 15:07
Doors are assigned a unique hash, and the state is synced to that hash; the entity is assigned to the door when you move in range, based on the hash and coordinates.

If the door is locked but still in an open position for a client, other clients who come in range will see it closed and frozen; could be that. Otherwise, maybe the door didn’t swing all the way shut for that client?

Do the doors lock once pushed into the correct position? Do they lock when leaving the area and coming back?

**Comment by Baxxster** [comment] 2022-05-19 15:22
For some both doors are frozen and locked.
For some only one of the two doors are frozen and locked.

I actually got a report from a player today as well saying that a single door did show "locked" but you can open it freely, it's not frozen. And unlocking/locking it doesn't change that at all, nor swinging it into default position

Trying to re-swing the doors into the correct position doesn't work either when they're behaving like this.

I haven't found any consistent pattern to test this, all I know is that it differs from player to player, a relog can fix it for a period of time.

I think I'm going to make a command to check IsDoorRegisteredWithSystem, to see if this is the problem unless you suggest me testing other methods too

**Comment by thelindat** [comment] 2022-05-30 00:36
@Baxxster is this issue still occurring? I made a change a week ago that might have been related.

**Comment by Baxxster** [comment] 2022-05-30 01:10
Yes, I'm still having the issues, have been following your updates and applied the patches to our code.

IsDoorRegisteredWithSystem(hash) says the door is registered.. and trying to re-add the door with AddDoorToSystem() does not work either..

Do you have any clue why this might happen? I'm thinking this is outside the scope of this script, maybe related to OneSync somehow?

We used ng_doorlocks previously without errors, though they didn't use the door system, it froze entities based of coords.

**Comment by meltynetv2** [comment] 2022-06-25 22:06
I am as well getting this issue. It happened today when adding a new door specifically a double door at the casino by gabz. It is the front door double doors. I add both doors through /doorlock and once selecting them both with qtarget it shows the door is locked but the left door is left open.

I am not sure what is the issue, happens when on the job for the door I'm adding and not on the job.

**Comment by meltynetv2** [comment] 2022-06-27 21:43
> I am as well getting this issue. It happened today when adding a new door specifically a double door at the casino by gabz. It is the front door double doors. I add both doors through /doorlock and once selecting them both with qtarget it shows the door is locked but the left door is left open.
> 
> I am not sure what is the issue, happens when on the job for the door I'm adding and not on the job.

Actually I think this bug may have to do with broken MLO doors. Are you experiencing this bug only on MLO doors @Baxxster ?

If so, I believe it's bad MLO doors that are doing it as I tried with nui_doorlock on the same doors that I said were broken above and they still don't work(which all doors work with nui_doorlock for me). The MLO must be a problem in my case, not sure about OP. Hopefully you can find a solution to this problem the OP is having, thanks.

**Comment by Baxxster** [comment] 2022-06-28 23:39
Not only in my case, it has happened to vanilla doors/gates on my server

**Comment by aiden-28** [comment] 2022-07-16 12:40
i have this issue on sinnerPD the cell doors

**Comment by benzon** [comment] 2022-07-20 14:12
@Baxxster @aiden-28 

Noticed that Linden pushed a attempt to fix the issue, try out his changes, to client/main.lua and see if that works.

**Comment by Baxxster** [comment] 2022-07-20 14:17
Changing the code here now, will know more after my scheduled restart 02:00 tonight if it works or not :)

**Comment by juddisjudd** [comment] 2022-07-21 00:20
Tested on Vanilla/Fresh ox_core, qbcore and esx servers and unable to reproduce the issue.
https://streamable.com/ug5riu

**Comment by thelindat** [comment] 2022-07-24 04:13
> Changing the code here now, will know more after my scheduled restart 02:00 tonight if it works or not :)

Any news?

**Comment by Baxxster** [comment] 2022-07-24 20:06
> > Changing the code here now, will know more after my scheduled restart 02:00 tonight if it works or not :)
> 
> Any news?

My players are still having this issue sadly.

**Comment by Baxxster** [comment] 2022-07-25 14:31
Also tried the newest addition to ignore heading of the doors, this leads to door being stuck in the position they're locked in. Aka, door won't swing to a close before it locks.

[https://i.gyazo.com/thumb/1200/11330e949e26bc2bd04e21bb33d949b9-jpg.jpg](https://i.gyazo.com/thumb/1200/11330e949e26bc2bd04e21bb33d949b9-jpg.jpg)

**Comment by thelindat** [comment] 2022-07-25 21:01
That’s what the heading check was for. With this hopefully temporary change you need to move it to a closed position, or it needs to be moving towards it already. They should eventually start to swing closed otherwise.

**Comment by thelindat** [comment] 2022-07-26 23:06
> Also tried the newest addition to ignore heading of the doors, this leads to door being stuck in the position they're locked in. Aka, door won't swing to a close before it locks.
> 
> https://i.gyazo.com/thumb/1200/11330e949e26bc2bd04e21bb33d949b9-jpg.jpg

Try the following event (replace the current one). If it doesn't work than I'm not sure what to do.
Previously it was getting stuck in the loop, or silently failing. Maybe a fresh set of eyes will see what I messed up, if this doesn't work.

~~removed~~

**Comment by Baxxster** [comment] 2022-07-27 03:47
Testing it out today, asking my playerbase to give me feedback.
@ me if I forget to reply within a couple of days :)

**Comment by thelindat** [comment] 2022-07-27 03:50
> Testing it out today, asking my playerbase to give me feedback. @ me if I forget to reply within a couple of days :)

Somebody else tested and it apparently didn't work, but his repro is also.. odd (and doesn't work for me).
Toggling doors works until he triggers the event from another resource, which breaks locking.

Probably going to have to look into applying force to the door or something.. I don't even know.

**Comment by Baxxster** [comment] 2022-07-27 04:02
We don't trigger the event outside the resource itself.
I know in the old scripts that froze entities they were frozen into a specific heading, but I guess that defeats the purpose with the doorsystem itself

**Comment by thelindat** [comment] 2022-07-31 03:13
> Testing it out today, asking my playerbase to give me feedback. @ me if I forget to reply within a couple of days :)

@Baxxster

**Comment by Baxxster** [comment] 2022-07-31 05:19
We got the same problem with the patch, so I went back to the old one without heading check, it seems persistent, though it requries more user-interaction

**Comment by jag3dagster** [comment] 2022-08-07 04:07
@thelindat is there a world wherein this is some nasty race condition of double[1] getting loaded in, but within the microsecond of the check for double[2]'s entity it isn't fully loaded in yet, so the loop breaks out of checking / setting entities for that door and therefore the second door will forever swing because it was never given an entity to check for / set the lock status of?

Edit: This would only happen if the render distance of the door was < 80 units I suppose...

ox_doorlock\client\main.lua @ ln. 52
```lua
if door.distance < 80 then
    if not double[1].entity and IsModelValid(double[1].model) and IsModelValid(double[2].model) then
        for i = 1, 2 do
            local entity = GetClosestObjectOfType(double[i].coords.x, double[i].coords.y, double[i].coords.z, 1.0, double[i].model, false, false, false)

            if entity ~= 0 then
                double[i].entity = entity
                Entity(entity).state.doorId = door.id
            end
        end
    end

    if door.distance < 20 then
        nearbyDoors[#nearbyDoors + 1] = door
    end
elseif double[1].entity then
    for i = 1, 2 do
        double[i].entity = nil
    end
end
```

**Comment by jag3dagster** [comment] 2022-08-07 04:40
If I set that for loop to `for i = 1, 1 do` I am able to repro the issue and have a single door lock and the other swing freely.

**Comment by thelindat** [comment] 2022-08-07 04:53
Considering nothing is truly asynchronous and all happens in order it’s odd that one door would have an entity and not another; but I also have no other thoughts on the cause.

**Comment by thelindat** [comment] 2022-08-07 05:13
@Baxxster 

Lines 51->72
```lua
			if double then
				if door.distance < 80 then
					for i = 1, 2 do
						if not double[i].entity and IsModelValid(double[i].model) then
							local entity = GetClosestObjectOfType(double[i].coords.x, double[i].coords.y, double[i].coords.z, 1.0, double[i].model, false, false, false)

							if entity ~= 0 then
								double[i].entity = entity
								Entity(entity).state.doorId = door.id
							end
						end
					end

					if door.distance < 20 then
						nearbyDoors[#nearbyDoors + 1] = door
					end
				else
					for i = 1, 2 do
						double[i].entity = nil
					end
				end
			elseif door.distance < 80 then
```

```lua
RegisterNetEvent('ox_doorlock:setState', function(id, state, source, data)
	if not doors then return end

	if data then
		doors[id] = data
		createDoor(data)
	end

	if Config.Notify and source == cache.serverId then
		if state == 0 then
			lib.notify({
				type = 'success',
				icon = 'unlock',
				description = locale('unlocked_door')
			})
		else
			lib.notify({
				type = 'success',
				icon = 'lock',
				description = locale('locked_door')
			})
		end
	end

	local door = data or doors[id]
	local double = door.doors
	door.state = state

	if double then
		if double[1].entity and not door.auto and door.state == 1 then
			while double[1].entity and double[2].entity do
				if door.state ~= 1 then return end

				local doorOneHeading = double[1].heading
				local doorOneCurrentHeading = math.floor(GetEntityHeading(double[1].entity) + 0.5)

				if doorOneHeading == doorOneCurrentHeading then
					DoorSystemSetDoorState(double[1].hash, door.state, false, false)
				end

				local doorTwoHeading = double[2].heading
				local doorTwoCurrentHeading = math.floor(GetEntityHeading(double[2].entity) + 0.5)

				if doorTwoHeading == doorTwoCurrentHeading then
					DoorSystemSetDoorState(double[2].hash, door.state, false, false)
				end

				if doorOneHeading == doorOneCurrentHeading and doorTwoHeading == doorTwoCurrentHeading then break end
				Wait(0)
			end
		end

		for i = 1, 2 do
			DoorSystemSetDoorState(double[i].hash, door.state, false, false)
		end
	else
		if door.entity and not door.auto and door.state == 1 then
			while door.entity do
				if door.state ~= 1 then return end

				local heading = math.floor(GetEntityHeading(door.entity) + 0.5)

				if heading == door.heading then break end
				Wait(0)
			end
		end

		DoorSystemSetDoorState(door.hash, door.state, false, false)
	end

	if door.state == state and door.distance and door.distance < 20 then
		local volume = (0.01 * GetProfileSetting(300)) / (door.distance / 2)
		if volume > 1 then volume = 1 end
		local sound = state == 0 and door.unlockSound or door.lockSound or 'door-bolt-4'

		SendNUIMessage({
			action = 'playSound',
			data = {
				sound = sound,
				volume = volume
			}
		})
	end
end)
```

**Comment by jag3dagster** [comment] 2022-08-07 05:30
~~Without updating the conditional on line 54 within `ox_doorlock:setDoors` event even with this snippet, it's possible they'll hit the same issue.~~

**Comment by thelindat** [comment] 2022-08-07 05:32
Not sure why one door would be loaded and not another, but the heading check will end if either entity is nil.

**Comment by jag3dagster** [comment] 2022-08-07 05:40
Ah I see what you're saying. I forgot `DoorSystem` doesn't technically care about the entity itself, only a specified model near a specified location. Disregard my point.

However, exiting out of the loop early if an entity is missing does mean that we continue to have the issue of a single door taking forever to close / staying open. I know it's weird, but I have to believe there is a weird race condition where one of the entities is nil and the other isn't.

**Comment by thelindat** [comment] 2022-08-20 09:32
Going to assume it's fixed until otherwise reported.

**Comment by thelindat** [comment] 2022-11-16 23:52
Reopening because it was reported again recently, so changes were reverted (and so doors no longer swing at all, currently).

**Comment by jag3dagster** [comment] 2022-11-17 00:40
Here is forum post that I wrote-up detailing the R* natives behavior: https://forum.cfx.re/t/adddoortosystem-native-rounds-x-y-z-values-to-integers/4936121/3

Been nearly a month at this point with no communication beyond 'put this in a different spot'.

**Comment by rhyfii** [comment] 2023-01-14 07:10
I've had the same issue and noticed that whenever 'automatic' is toggled (when setting an automatic moving door) it seems to randomly apply this setting to other doors previous to its creation including the 'door rate'. 

I've tested it a few times with the same result. I'd imagine having doors assigned as 'automatic' when they're not meant to be could cause issues. Ever since I've fixed this on my server I haven't had the issue where a double door wouldn't lock. 

I also noticed that if you set a door to 'automatic' when its not supposed to be, if you hold the door open and it auto locks, it will apply the 'door rate' and shut very slowly. In some instances it could even stop the door completely. 

Just some thoughts. Hopefully it can help resolve the issue

**Comment by thelindat** [comment] 2023-01-14 12:02
> I also noticed that if you set a door to 'automatic' when its not supposed to be, if you hold the door open and it auto locks, it will apply the 'door rate' and shut very slowly. In some instances it could even stop the door completely.

All the "auto" field does is determine if the door state should be applied immediately, or when the door heading is close to the closed heading. Hence the following quote

> Using DoorSystemSetDoorState to set a door to state 1 (locked) disables door swinging, thus needs to be pushed closed before properly locking.

The heading check was temporarily removed but then I got (even more) complaints because of the lack of door swinging.

**Comment by Manason** [comment] 2023-01-14 15:50
> I've had the same issue and noticed that whenever 'automatic' is toggled (when setting an automatic moving door) it seems to randomly apply this setting to other doors previous to its creation including the 'door rate'.
> 
> I've tested it a few times with the same result. I'd imagine having doors assigned as 'automatic' when they're not meant to be could cause issues. Ever since I've fixed this on my server I haven't had the issue where a double door wouldn't lock.
> 
> I also noticed that if you set a door to 'automatic' when its not supposed to be, if you hold the door open and it auto locks, it will apply the 'door rate' and shut very slowly. In some instances it could even stop the door completely.
> 
> Just some thoughts. Hopefully it can help resolve the issue

I ran into the same issue of a setting (I think it was lock) being applied to other doors when creating a new door. This occurred after I upgraded from v1.7.0 to v.1.8.2 so we rolled back the update and restored database from backup. We edited some of the lock pick code so I figured we introduced an incompatible change with v1.8.2 but reading the above I'm no longer sure about that.

**Comment by rhyfii** [comment] 2023-01-18 04:15
> > I also noticed that if you set a door to 'automatic' when its not supposed to be, if you hold the door open and it auto locks, it will apply the 'door rate' and shut very slowly. In some instances it could even stop the door completely.
> 
> All the "auto" field does is determine if the door state should be applied immediately, or when the door heading is close to the closed heading. Hence the following quote
> 
> > Using DoorSystemSetDoorState to set a door to state 1 (locked) disables door swinging, thus needs to be pushed closed before properly locking.
> 
> The heading check was temporarily removed but then I got (even more) complaints because of the lack of door swinging.

The 'doorrate' being set in conjunction with the 'automatic' toggle is more the issue, with doors being stuck open (I've tested this). Besides, I'd imagine the input data should be cleared after setting a new door. It seems to be carrying over to the new door that is being set

**Comment by rhyfii** [comment] 2023-01-18 04:17
> > I've had the same issue and noticed that whenever 'automatic' is toggled (when setting an automatic moving door) it seems to randomly apply this setting to other doors previous to its creation including the 'door rate'.
> > I've tested it a few times with the same result. I'd imagine having doors assigned as 'automatic' when they're not meant to be could cause issues. Ever since I've fixed this on my server I haven't had the issue where a double door wouldn't lock.
> > I also noticed that if you set a door to 'automatic' when its not supposed to be, if you hold the door open and it auto locks, it will apply the 'door rate' and shut very slowly. In some instances it could even stop the door completely.
> > Just some thoughts. Hopefully it can help resolve the issue
> 
> I ran into the same issue of a setting (I think it was lock) being applied to other doors when creating a new door. This occurred after I upgraded from v1.7.0 to v.1.8.2 so we rolled back the update and restored database from backup. We edited some of the lock pick code so I figured we introduced an incompatible change with v1.8.2 but reading the above I'm no longer sure about that.

Yeah, even sounds can carry over to new doors being set. I've started restarting the script after every door created

**Comment by thelindat** [comment] 2023-01-20 02:22
> Besides, I'd imagine the input data should be cleared after setting a new door. It seems to be carrying over to the new door that is being set

> Yeah, even sounds can carry over to new doors being set. I've started restarting the script after every door created

Nothing is being carried over when I'm testing.

**Comment by thelindat** [comment] 2023-03-26 20:28
Closed for now since it's dead and assumed resolved.

**Closed as completed by thelindat** 2023-03-26 20:28 UTC
Labels: bug, question
