### ISSUE TITLE
i use only steam identifier 

### ISSUE THREAD

**Issue by soulofzephir** [overextended/ox_doorlock#140] opened 2023-05-16 11:00 UTC
i use only steam identifier and its save as 110000119ed5xxx not steam:110000119ed5xxx but when i enter the identifier its not save 110000119 what shoul i do?

**Comment by thelindat** [comment] 2023-05-16 11:26
... duplicate of https://github.com/overextended/ox_doorlock/issues/139 (not hard to see???)

**Closed as not planned by thelindat** 2023-05-16 11:26 UTC
